[build]
publish = "public"
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_URL"

[context.production]
command = "hugo -b $URL"

[[redirects]]
from = "/xxx"
to = "https://qib17.quarteera.de"
status = 301

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/404.html"
status = 404